### ISSUE TITLE
Add android development resource.

### ISSUE THREAD

**Issue by Koustavjr** [WeMakeDevs/roadmaps#280]
### Description

I want to add android development resource.

**Comment by Koustavjr** [comment]
@siddhant-khisty can u please assign me this issue

**Comment by siddhant-khisty** [comment]
Please mention what resource would you like to add

**Comment by Koustavjr** [comment]
> Please mention what resource would you like to add

I would love to add Kotlin resource by freecodecamp.

**Comment by siddhant-khisty** [comment]
Please open a PR and link this issue there as well
