### ISSUE TITLE
[FEATURE] Add Linux Masterclass Course - Beginner to Advanced

### ISSUE THREAD

**Issue by abhishekchandra2522k** [WeMakeDevs/roadmaps#296]
### Description

Add Linux Masterclass Course - A complete tutorial from Beginner to Advanced from Apoorv Goyal to the DevOps roadmap in the Linux section.

### Screenshots

![image](https://user-images.githubusercontent.com/51490584/203138852-d7ebb9ef-94ae-4f72-83c8-c6d3f8bd00fc.png)

**Comment by siddhant-khisty** [comment]
Hey @abhishekchandra2522k this is a great addition. Please feel free to open a PR for the same. Just a heads up, Linux is mentioned in multiple roadmaps such as the DevOps, backend, and full-stack roadmaps (probably in others as well). Would be great if you could update there as well

**Comment by abhishekchandra2522k** [comment]
sure thing! I will raise a PR for the same by EOD.
