### ISSUE TITLE
Replace the community classroom links by WeMakeDevs links

### ISSUE THREAD

**Issue by AnuragThePathak** [WeMakeDevs/roadmaps#300]
Change of mention of Community Classroom to WeMakeDevs is also appreciated.

**Comment by abhishekchandra2522k** [comment]
I would like to work on this issue. Can you please assign it to me? 
It will be my first issue to work on so I would need some guidance, and I also want to gain some git knowledge about issues and PRs along the way!

**Comment by abhishekchandra2522k** [comment]
Thank you! I will check this repo thoroughly and make the changes asap.

**Comment by abhishekchandra2522k** [comment]
https://github.com/WeMakeDevs/roadmaps/blob/696f3c8c87720c5bc1379a56b44e99bd9ef8c885/DevRel/Readme.md?plain=1#L47

Hi, just wanted to know that should I change the `commclassroom` keyword in these types of links to `wemakedevs` or wait till the `wemakedevs.org` will be up and running.

**Comment by shivaabhishek07** [comment]
I too would like to work on this issue. Can I make changes and collaboratively make the changes with @abhishekchandra2522k?

**Comment by AnuragThePathak** [comment]
Eh I think the issue is too simple to work for two persons.

**Comment by shivaabhishek07** [comment]
> Eh I think the issue is too simple to work for two persons.
Yeah, working on the issue that needs keen observation in every corner makes the work easy and fast when we have more people working on it I guess.

**Comment by shivaabhishek07** [comment]
> Eh I think the issue is too simple to work for two persons.

Yeah, working on the issue that needs keen observation in every corner makes the work easy and fast when we have more people working on it I guess.

**Comment by siddhant-khisty** [comment]
@abhishekchandra2522k all instances of `commclassroom` will need to be changed to `WeMakeDevs`. Please edit any instance you see
