### ISSUE TITLE
[OTHER] Missing playlist 

### ISSUE THREAD

**Issue by VishwaS-22** [WeMakeDevs/roadmaps#309]
### One of the Sample Projects Playlist is missing in the DevOps roadmap!

Hey there! In DevOps roadmap at the final stage of DevOps Sample Projects,  The "20 DevOps Real-time Projects" videos is not available in the respective youtube channel. So please check with that! Kindly add alternate resources for the reference. Happy to contribute.

Thankyou.
![Screenshot (162)](https://user-images.githubusercontent.com/85573504/203791088-d792c085-38af-48c5-b953-9f9bb8b6bc6f.png)

**Comment by siddhant-khisty** [comment]
hmm. I guess the creator removed the videos. Please open a PR to remove this resource. If you know of anything to replace this with, please include that as well in the PR

**Comment by VishwaS-22** [comment]
Hey @siddhant-khisty! Sure, Please assign this issue to me. I would like to work on this.

Thankyou!

**Comment by VishwaS-22** [comment]
Hey @siddhant-khisty! Yeah bro added the link and made a PR. Please check it.

Thankyou!
