### ISSUE TITLE
[FEATURE] <description>

### ISSUE THREAD

**Issue by Shikharishere** [WeMakeDevs/roadmaps#311]
### Description

A roadmap for machine learning would be a great addition.

**Comment by Sunnyjoe101** [comment]
What can I do to be of help?

**Comment by VishwaS-22** [comment]
Hey @Sunnyjoe101! Fork this repo and Create a separate folder for Machine Learning roadmap then add the steps with proper resources and make PR. That's it. Hope this clears your doubt.

Thankyou!

**Comment by VishwaS-22** [comment]
Hey @Shikharishere! Please change the title of the ISSUE from "description" to "ML roadmap". Because it leads to open an another Issue for the same purpose. So please change it.

Thankyou!

**Comment by siddhant-khisty** [comment]
Duplicate issue
