### ISSUE TITLE
Al and ML

### ISSUE THREAD

**Issue by 1nevil** [WeMakeDevs/roadmaps#314]
### Description

if any developer is expert in ai ml can you just add a roadmap of ai ml roadmap and also good resources.

**Comment by ankkol2011** [comment]
can't we use [this](https://www.youtube.com/playlist?list=PLyzHIYrZBplo3K0dNUqppd2ynnoZPD6N1) playlist of Kunal on AI & ML as a starting point.

**Comment by 1nevil** [comment]
we all need this repository kind of roadmap and resources in ai and ml. industry's best creators of youtube resources like web development already have.

**Comment by Vishvsalvi** [comment]
Hello guys, any one interested to collaborate w me to create the ML roadmap?

**Comment by AniketNS** [comment]
@Vishvsalvi, I would love to work with you. Please assign this to me.

**Comment by suryanshsoni120** [comment]
I would also like to collaborate.

**Comment by Vishvsalvi** [comment]
That's great guys, we need to inform maintainers first coz they are busy and barely pay any attention in this roadmap

**Comment by sonustar** [comment]
can i contribute a roadmap for ML

**Comment by prakashvishal93** [comment]
I also want to contribute on this isssue

**Comment by KaKashi1210** [comment]
Hey @1nevil  can you assign this issue to me would love to contribute

**Comment by 1nevil** [comment]
how I will assign it @KaKashi1210   @sonustar @prakashvishal93 ?

**Comment by 1nevil** [comment]
sorry by mistake closed issue sorry for that.

**Comment by Keerthi-prasanna-Sa** [comment]
I would also love to contribute to this issue. How can I contribute?

**Comment by abhigyan631** [comment]
Is this issue still open? I would like to contribute my part.
