### ISSUE TITLE
[FEATURE] Add React Router v6 & React Redux to the Frontend roadmap.

### ISSUE THREAD

**Issue by debrajhyper** [WeMakeDevs/roadmaps#319]
### Description

Hello! I'm opening this issue so that the React Router v6 & React Redux tutorials can be added to the Frontend roadmap. However, it is not included on the Frontend roadmap, even though it is necessary to learn.

link to the resources
- [Codevolution](https://www.youtube.com/playlist?list=PLC3y8-rFHvwjkxt8TOteFdT_YmzwpBlrG)
- [Codevolution](https://www.youtube.com/playlist?list=PLC3y8-rFHvwheJHvseC3I0HuYI2f46oAK)

### Screenshots

![Capture](https://user-images.githubusercontent.com/64654268/208226328-2f0ca2f3-a829-46c3-ba4b-2324bece6af5.PNG)
![Capture2](https://user-images.githubusercontent.com/64654268/208226358-9e73bb13-27f2-42be-8125-25b00cdfca9c.PNG)

### Additional information

I would like to work on this issue. So please assign this to me.

Thankyou!

**Comment by debrajhyper** [comment]
any updates @kaiwalyakoparkar

**Comment by siddhant-khisty** [comment]
Hey @debrajhyper, feel free to open a PR for the same.
