### ISSUE TITLE
[Bug] Typo in DevRel with Kunal's name

### ISSUE THREAD

**Issue by thisisheymde** [WeMakeDevs/roadmaps#320]
### Description

In [this](https://github.com/WeMakeDevs/roadmaps/tree/main/DevRel#all-about-devrel) and [this](https://github.com/WeMakeDevs/roadmaps/tree/main/DevRel#programs) section, Kunal's last name is spelt wrong. It is supposed to be Kushwaha (afaik), but it is spelt Khushwaha there. 

### Screenshots

![image](https://user-images.githubusercontent.com/99078610/208258474-0dce48d1-7162-4356-ab76-5ac8217e1c5e.png)
![image](https://user-images.githubusercontent.com/99078610/208258524-eb0c7123-f0fa-4f11-b641-9ed9e137eac3.png)

**Comment by kaiwalyakoparkar** [comment]
@thisisheymde image is not rendering, please fix that so we can confirm the issue

**Comment by thisisheymde** [comment]
@kaiwalyakoparkar I've updated the original comment. Would you mind checking again please?

**Comment by kelvinparmar** [comment]
I would like to fix this issue

**Comment by siddhant-khisty** [comment]
@kelvinparmar feel free to open a PR for the same
