### ISSUE TITLE
To add Data Analyst roadmap

### ISSUE THREAD

**Issue by AyushJain001** [WeMakeDevs/roadmaps#321]
### Description

I would love to help people grow in data science career and would like to add roadmaps to existing repository for Data Analyst roadmap.

**Comment by AyushJain001** [comment]
@kunal-kushwaha  May you please assign this issue. I would like to work on this

**Comment by siddhant-khisty** [comment]
@AyushJain001 Go ahead. Please follow the formatting used in the other roadmaps

**Comment by AyushJain001** [comment]
okay, I will soon be making PR for the same

**Comment by abhigyan631** [comment]
Is this issue still open or anyone is working on it ? Thank you.
