### ISSUE TITLE
[Bug] <"25+ paid open source programs and internships - WeMakeDevs" link is not working.>

### ISSUE THREAD

**Issue by Sarvesh-Kesharwani** [WeMakeDevs/roadmaps#322]
### Description

the link is broken.

### Screenshots

![chrome_qByi2xISVm](https://user-images.githubusercontent.com/22115102/209426774-0069398d-8e2f-4c14-9067-ebb3ee01afd6.png)

**Comment by Sarvesh-Kesharwani** [comment]
can someone assign this issue to me, i want to contribute.

**Comment by siddhant-khisty** [comment]
Hey @Sarvesh-Kesharwani please feel free to work on this. The blog you are referring to has been shifted to https://blog.wemakedevs.org/

Please update the link for the same. Thanks

**Comment by Sarvesh-Kesharwani** [comment]
thanx for replying, i'll do it.
