### ISSUE TITLE
[Blockchain roadmap] Additional resources regarding blockchain project 

### ISSUE THREAD

**Issue by payalpagaria** [WeMakeDevs/roadmaps#327]
### Description

Addition of one project based learning resource in blockchain roadmap (video format).

**Comment by siddhant-khisty** [comment]
Hey @payalpagaria please open a PR for the same

**Comment by payalpagaria** [comment]
i have done that please check it once

**Comment by siddhant-khisty** [comment]
@payalpagaria please link your PR's with the relevant issue number. :)
