### ISSUE TITLE
The link to website is incorrect

### ISSUE THREAD

**Issue by 31Sanskrati** [WeMakeDevs/roadmaps#333]
### Description

In the repository, the link to the website given in the about section is as https://www.wemakedevs.org/ which is not working instead the correct link is https://wemakedevs.org/

### Screenshots

![Screenshot 2023-01-03 225819](https://user-images.githubusercontent.com/78686887/210409586-010798ef-8ab4-4c66-a35e-a00a1312d394.jpg)
![Screenshot 2023-01-03 225905](https://user-images.githubusercontent.com/78686887/210409708-d94756a2-0873-4b1c-9a51-4d5aaab4133d.jpg)

**Comment by siddhant-khisty** [comment]
Hey @31Sanskrati feel free to open a PR for the same

**Comment by 31Sanskrati** [comment]
There isn't a way to create a pull request for changes in the repository description. If there is any way, please inform me

**Comment by siddhant-khisty** [comment]
oh got it. Thanks for pointing it out. I thought you were referring to a link in the readme file :sweat_smile:

**Comment by munnokd** [comment]
Still this website dont work so please fix this bug.

**Comment by SharmaDhruv2511** [comment]
I am have solve the bug but not able to raise a PR. Can you please help me?

**Comment by 31Sanskrati** [comment]
The bug can't be solved by PR. It can only be solved by the admin of this repository as the website link is present in the description
