### ISSUE TITLE
Hackathon Links

### ISSUE THREAD

**Issue by BharatSharma29** [WeMakeDevs/roadmaps#357]
### Description

It will be great if we could post links of hackathons which happen every year for all the roles

**Comment by suryanshsoni120** [comment]
We can add hackathons with description, application link, eligibility and tentative schedule.
I can add a few hackathons.

**Comment by siddhant-khisty** [comment]
I don't think hackathons should be included in the roadmap as they are great for practice and incentives for building stuff, but not a mandatory requirement. Moreover, hackathons are mostly a one-time thing. It would be better if folks search for hackathons on websites such as Devpost. You can include the general Devpost or Devfolio links with domain-specific filters. That would be better imp

**Comment by BharatSharma29** [comment]
> I don't think hackathons should be included in the roadmap as they are great for practice and incentives for building stuff, but not a mandatory requirement. Moreover, hackathons are mostly a one-time thing. It would be better if folks search for hackathons on websites such as Devpost. You can include the general Devpost or Devfolio links with domain-specific filters. That would be better imp

Personally hackathons are great way to test and showcase skills Plus you also get to network with multiple people

**Comment by siddhant-khisty** [comment]
@BharatSharma29 I agree with that point. You can add the main hackathon home pages. devpost homepage for example at the end of every roadmap. It can be in a section called `Find Hackathons`
