### ISSUE TITLE
[Blockchain roadmap] Links to hackathons that happens every year in Web3 space

### ISSUE THREAD

**Issue by BharatSharma29** [WeMakeDevs/roadmaps#358]
### Which field of community (DevOps/Opensource/Web/Web3/Android/Devrel) you want to add, drop the links?

Web3

[Chainlink Hackathon](https://chain.link/hackathon)

[Eth Global](https://ethglobal.co/)

[Eth India](https://twitter.com/ETHIndiaco)

**Comment by ArslanYM** [comment]
Can I work on this issue?

**Comment by siddhant-khisty** [comment]
@ArslanYM I belive this is an old issue that has already been merged. Sorry about that. Closing it now.
