### ISSUE TITLE
[Bug] Broken Community Discord link

### ISSUE THREAD

**Issue by Saga-sanga** [WeMakeDevs/roadmaps#359]
### Description

The discord link for the CS Dojo open source community is broken. It seems to me that there is a typo in the link.

**Comment by siddhant-khisty** [comment]
It was probably an expiring link that was put in there. Please create a permanent link and raise a PR for the same :)

**Comment by nakulbh** [comment]
I have updated the cs dojo community discord server link its a permanent link now. I have raised a PR please review
