### ISSUE TITLE
[DevOps Roadmap] Additional K8s resource

### ISSUE THREAD

**Issue by SD-13** [WeMakeDevs/roadmaps#368]
### Description

What do you think about adding [KubeCampus](https://kubecampus.io/) in `Kubernetes` section under [Container Orchestration](https://github.com/WeMakeDevs/roadmaps/tree/main/DevOps#container-orchestration)?

**Comment by SD-13** [comment]
@siddhant-khisty @kaiwalyakoparkar, Hey I found the KubeCampus stuff really useful and for that, I created this issue. Please let me know what you think about this. Thanks,

**Comment by siddhant-khisty** [comment]
Hey @SD-13, I've heard about this resource and that it's great. Could you please confirm if it's a free resource? We're not including any paid resources or paid courses in this repo. If it's free, then please feel free to open a PR for the same 😄

**Comment by SD-13** [comment]
Hey @siddhant-khisty, yeah I can confirm that it's totally free and that's why I mentioned it here. Will create a PR for this soon🚀
