### ISSUE TITLE
[FEATURE] <A website for Practicing HTML,CSS & JS through mini projects>

### ISSUE THREAD

**Issue by Chayannn** [WeMakeDevs/roadmaps#372]
### Description

I want to add  FlorinPops iCodeThis website to the Frontend Projects section of Frontend Development.
Here's the Link: https://www.icodethis.com

**Comment by siddhant-khisty** [comment]
Looks good. Feel free to open a PR for the same

**Comment by Chayannn** [comment]
Yeah, I have opened a PR. Please review it.

**Comment by WillOfHeaven** [comment]
I would really like to mentor this platform for practicing
frontend development , frontendmentor.io Please do check it out and let me
know about whether you like it or not ?
