### ISSUE TITLE
Invalid Community link in Android Dev

### ISSUE THREAD

**Issue by Rup-Royofficial** [WeMakeDevs/roadmaps#381]
### Description

The discord  link for **AndroidDev** within the community folder in Android dev roadmap is invalid or might have expired

### Screenshots

![image](https://user-images.githubusercontent.com/76125011/214323798-0915c6c7-9de4-43dd-aeeb-76b5566fa10a.png)
![image](https://user-images.githubusercontent.com/76125011/214323856-71625f99-3b02-4d59-8736-f268b56c1aaa.png)

**Comment by mohd-raza** [comment]
@siddhant-khisty  hey can you assign me to update this discord link

**Comment by siddhant-khisty** [comment]
Good catch. Please feel free to make a PR if someone is part of the server

**Comment by mohd-raza** [comment]
@siddhant-khisty Can I handle this issue?

**Comment by siddhant-khisty** [comment]
@mohd-raza sure. Please open a PR for the same and link the issue

**Comment by mohd-raza** [comment]
@siddhant-khisty hey I have fixed the issue and the discord link is a permanent one, could you please review it once. Thanks!

**Comment by mohd-raza** [comment]
Thanks @siddhant-khisty for merging the PR!
