### ISSUE TITLE
Website of wemakedevs is not working It can gives error.

### ISSUE THREAD

**Issue by munnokd** [WeMakeDevs/roadmaps#386]
### Description

Website of given wemakedevs is not working it can gives me a error in [https://www.wemakedevs.org/](url) this website

### Screenshots

![image](https://user-images.githubusercontent.com/81804004/214618180-8395da1a-e5ae-48b1-80d7-93acc46fcf9e.png)

**Comment by munnokd** [comment]
Please Fix this bug

**Comment by rahulpandey70** [comment]
Hey, @kunal-kushwaha WeMakeDevs server is down please fix that.

**Comment by siddhant-khisty** [comment]
Hey folks, the website is working. The problem is that you are using the `www` prefix. For some reason it does not work with that. This link will work for the website https://wemakedevs.org/

We're trying to figure out what's wrong with the `www` prefix.
