### ISSUE TITLE
[OTHER] <idk it is a bug or not >

### ISSUE THREAD

**Issue by nsundriyal62** [WeMakeDevs/roadmaps#390]
### Which field of community (DevOps/Opensource/Web/Web3/Android/Devrel) you want to add, drop the links?

i am working on an another  issue but 

after creating the server i faced this problem  

can anyone help me with this ....

![Screenshot from 2023-01-27 13-55-42](https://user-images.githubusercontent.com/69977405/215046342-420025bf-34ff-4265-9fcc-bda8b0f4f217.png)

**Comment by siddhant-khisty** [comment]
This isn't the correct repo.
