### ISSUE TITLE
Adding a Flutter Developer Roadmap

### ISSUE THREAD

**Issue by TRohit20** [WeMakeDevs/roadmaps#391]
### Description

Flutter allows you to build cross-platform application with single codebase which makes it a good choice for startups and projects that cannot afford to have two different native teams for app development. 

I'd like to request to build a flutter developer roadmap or I can build one with the help of a seasoned flutter developer. :)

**Comment by Dnyaneshvn** [comment]
+1

**Comment by siddhant-khisty** [comment]
Sure @TRohit20. PLease go ahead

**Comment by TRohit20** [comment]
Cool, Thank you assigning it to me. I will be working with few seasoned developers and build a good roadmap for anyone to get started. It'll take some time though. That should be okay?

**Comment by siddhant-khisty** [comment]
@TRohit20 Take your time. If the issue goes stale, I'll ask for updates. While you are creating the roadmap, you can also open a draft PR so we can keep a track of the progress. Thanks :smile:

**Comment by TRohit20** [comment]
I will mostly keep you In loop as I build the roadmap. I will open the PR for the same soon.

**Comment by TRohit20** [comment]
Hey @siddhant-khisty Sorry I have pretty occupied with other things so Had to focus somewhere else But I am back now and have begun working on the e roadmap repo. Will be opening a PR soon so you can keep track of the work and suggest any changes if any required too.

**Comment by AmanNegi** [comment]
Hey there, is anyone working on this? It's been inactive for a long time now. I would love to work on this issue.

**Comment by TRohit20** [comment]
Hi @AmanNegi , I am still working on the repository, I paused on it as I was busy with my primary tasks at hand, I will come around to finishing the roadmap by end of this month. I don't wanna create a roadmap in rush or haste and misguide learners. It's not healthy, rather late than wrong. I hope you understand. :)

You can also choose to collaborate on the same PR with me if you wish to contribute.

**Comment by AmanNegi** [comment]
Hey there, no issues if you are working on it that's great. Surely, let me know if I can help you with something.

**Comment by TRohit20** [comment]
@AmanNegi Roadmaps don't have to be one view, Please feel free to collaborate with me on the PR and input your knowledge, I will make changes or put them in place as I finish it by End of this month. :)
