### ISSUE TITLE
Additional resource for linux in Devops roadmap

### ISSUE THREAD

**Issue by BharatSharma29** [WeMakeDevs/roadmaps#404]
### Description

Additional resource for linux in Devops roadmap

**Comment by mehrdadbn9** [comment]
hi 
 can you assigned me this issue?
which kind of resource is better or recommended (gap of resource from your consideration)?

**Comment by VishalPraneeth** [comment]
Can I contribute to this issue and add a few links for Linux resources?

**Comment by karthiknadar1204** [comment]
I would like to work on this issue,i have a few links for this

**Comment by Virus2466** [comment]
I would like to work on this ,  I would like to add  few server management videos and some few others Linux videos like important commands and stuff .

**Comment by Saha-7** [comment]
@BharatSharma29 I don't think it's a good idea to add more resources in the Linux Section. It is already looking bloated & overwhelming too. Try to keep it short & simple, basic knowledge of Linux is way more than enough to get started.

Thank You
