### ISSUE TITLE
[Bug] Redirecting to wrong URL

### ISSUE THREAD

**Issue by Harsh3341** [WeMakeDevs/roadmaps#422]
### Description

NodeJs Microservices Redirecting to wrong URL [NodeJs Microservices](https://www.youtube.com/watch?v=kBzbKUirOFk)

The issue is in Backend-Development/README.md path, line 122

### Screenshots

![Bug Fix](https://user-images.githubusercontent.com/101264150/219366278-bbbdfe7e-8e90-4dbe-beba-3b37c82ff647.JPG)

**Comment by Sandeep-RN** [comment]
This BUG is Fixed, so I think this issue should be closed.
