### ISSUE TITLE
Add SHELL Scripting resources

### ISSUE THREAD

**Issue by Saha-7** [WeMakeDevs/roadmaps#434]
### Description

As DevOps is all about automation & to avoid the repetitive task, SHELL Scripting knowledge is mandatory for the folks.

* Add some beginner-friendly to advanced-level resources for this -

**Comment by kaiwalyakoparkar** [comment]
Great idea @Saha-7. Would you like to add resources links in the issue discription so someone (or you) can go ahead and create pr for same.

**Comment by Saha-7** [comment]
Sure, I will. Please assign it to me.

**Comment by kaiwalyakoparkar** [comment]
@Saha-7 sure, can you please add the resouces in the issue discription so we can review it maybe?

**Comment by siddhant-khisty** [comment]
PR has been merged so closing the issue
