### ISSUE TITLE
To Add Freecodecamp's New linux course - Introduction to Linux – Full Course for Beginners

### ISSUE THREAD

**Issue by itsshahinhere** [WeMakeDevs/roadmaps#435]
### Which field of community (DevOps/Opensource/Web/Web3/Android/Devrel) you want to add, drop the links?

- Field of community = DevOps

- [Introduction to Linux – Full Course for Beginners By FreeCodeCamp](https://youtu.be/sWbUDq4S6Y8)

I really found this course to be so useful for learning the basic fundamentals of linux
Its free and valuable resource.
Kindly assign/approve this issue if it met the requirements, so i can create a PR for adding this link.

Thank you! Happy Learning !

**Comment by siddhant-khisty** [comment]
Sounds good. @itsshahinhere please feel free to open a PR adding this under Fullstack, backend and DevOps roadmaps' Linux sections

**Comment by itsshahinhere** [comment]
ok

**Comment by siddhant-khisty** [comment]
Closing as completed
