### ISSUE TITLE
[OTHER] < Typo error in iOS development roadmap>

### ISSUE THREAD

**Issue by Thiru-09** [WeMakeDevs/roadmaps#447]
### Which field of community (DevOps/Opensource/Web/Web3/Android/Devrel) you want to add, drop the links?

Hey Maintainers!

Opening an issue for fixing the typo error in iOS development roadmap, adding an image for reference, do check.
Happy to contribute, Thank You! 

<img width="1440" alt="Screenshot 2023-03-14 at 8 57 37 PM" src="https://user-images.githubusercontent.com/119996617/225053581-5726ae3f-3652-4560-9f90-e50d2eef516d.png">

**Comment by Sakthi511** [comment]
Hey Maintainers! I want to work on this issue; Please assign this to me to complete it!
Happy to contribute to our community! 
Thanks!

**Comment by Sandeep-RN** [comment]
Since this issue has been solved,
