### ISSUE TITLE
Increase Availability of Video Resources in the Blockchain Roadmap

### ISSUE THREAD

**Issue by tarunclub** [WeMakeDevs/roadmaps#453]
### Description

As the popularity of blockchain technology continues to grow, it's important that we have comprehensive resources available to learn about it. While there are many resources available online, video content is an increasingly popular medium for learning. However, the current blockchain roadmap lacks sufficient video resources to aid in understanding the technology. This issue is aimed at addressing this gap.

### Additional information

The addition of more video resources to the blockchain roadmap will make it more comprehensive and accessible to a wider range of learners. This will lead to a more informed and knowledgeable community around blockchain technology, and ultimately drive adoption and innovation.

I believe that adding more video resources to the blockchain roadmap is an important step towards creating a more inclusive and effective learning environment. I look forward to discussing this proposal with the community and working together to implement it.

**Comment by saikaia** [comment]
I think I can add some helpful videos regarfing this,Can you assign me this issue.

**Comment by siddhant-khisty** [comment]
Hey @tarunclub @saikaia, feel free to open a PR adding some resources. Please do take care of the following points though.
- The resources should be free.
- It should be coming from a credible source, i.e whoever has created the content must have real-world experience with blockchain.

**Comment by saikaia** [comment]
Hey, I have raised the PR for this issue.
Can you please review it.
