### ISSUE TITLE
[typo] <typo in backend end development roadmap, under docker. There should be boot.dev instead og boo.dev>

### ISSUE THREAD

**Issue by Bhanu-code** [WeMakeDevs/roadmaps#456]
### Which field of community (DevOps/Opensource/Web/Web3/Android/Devrel) you want to add, drop the links?
![Inkedwemakedev](https://user-images.githubusercontent.com/77599001/225977141-56991c1b-7781-4fe0-aede-616aa21b7dad.jpg)

Web

**Comment by ArslanYM** [comment]
Can  i Fix this?

**Comment by ArslanYM** [comment]
fixed in pr #459
