### ISSUE TITLE
Learn By Playing Games.

### ISSUE THREAD

**Issue by mnik7044** [WeMakeDevs/roadmaps#468]
### Which field of community (DevOps/Opensource/Web/Web3/Android/Devrel) you want to add, drop the links?

Web as far as I know but can be applicable to another field as well.

**Comment by mnik7044** [comment]
There are different ways to learn a skill I personally learned flexbox by playing a game and implementing the concepts, I want to add that part so that other students can also get a chance to follow this unique way of learning things

**Comment by mnik7044** [comment]
I would like to work on it please assign it to me.

**Comment by siddhant-khisty** [comment]
@mnik7044 not sure I get what you mean. Do you want to add a resource that helps learn stuff by gamifying the process? If so, can you share this resource?

**Comment by mnik7044** [comment]
Yes I meant the same here are some of the resources:
https://codingfantasy.com/games
https://flexboxfroggy.com/
https://cssgridgarden.com/
http://www.hexinvaders.com/

**Comment by mnik7044** [comment]
This might help many of the students who lose interest learning things or find any of the topic boring.

**Comment by siddhant-khisty** [comment]
Looks good. please feel free to open a Pr for the same

**Comment by mnik7044** [comment]
Hey @siddhant-khisty Do u want me to add the games of CSS in the CSS tutorial section game of js In js tutorial section and so on?

**Comment by mnik7044** [comment]
Oops sorry I didn't knew it, will take care of it in the future!
