### ISSUE TITLE
Add video resources to cloud provider section in DevOps roadmap

### ISSUE THREAD

**Issue by tarunclub** [WeMakeDevs/roadmaps#471]
### Description

Hi there,

I would like to suggest that video resources be added to the cloud provider section in the DevOps roadmap. I believe that video tutorials can be an effective way to learn about cloud providers, especially for visual learners.

It would be great to see videos covering popular cloud providers such as AWS, Azure, and Google Cloud Platform, as well as any up-and-coming providers. These videos could cover topics such as setting up infrastructure, deploying applications, and optimizing performance.

I recommend channels such as AWS Online Tech Talks, Microsoft Azure, and Google Cloud Platform for providing high-quality video content. Adding video resources to the DevOps roadmap could help make it a more comprehensive and valuable resource for those learning about DevOps and cloud computing.

Thank you for considering my suggestion!

**Comment by Vishsig** [comment]
I requested a PR for this issue today by adding the resources you mentioned.

**Comment by Vishsig** [comment]
I did a new PR for this issue. Creating a sub-section for video resources of DevOps cloud section.
