### ISSUE TITLE
[OTHER] Adding more OSS projects to contribute and learn from for iOS Development

### ISSUE THREAD

**Issue by TRohit20** [WeMakeDevs/roadmaps#472]
### Which field of community (DevOps/Opensource/Web/Web3/Android/Devrel) you want to add, drop the links?

iOS development

### For adding OpenSource Projects, add links here.

[Swift Official](https://github.com/apple/swift)
[DailyFeed](https://github.com/paulsumit1993/DailyFeed)
[OS-iOS-Apps](https://github.com/dkhamsing/open-source-ios-apps)

**Comment by TRohit20** [comment]
@siddhant-khisty , These are some useful repos and projects that are not included in the iOS development contribute section. They are not just projects to contribute but can be used to learn. Can you assign me the issue so I can go ahead and open a PR to resolve this?

**Comment by siddhant-khisty** [comment]
Hey @TRohit20, feel free to open a PR for this
