### ISSUE TITLE
[typo] <repository spelling mistake, it is 'ocrasound' instead of 'orcasound' in contribute section of frontend roadmap>

### ISSUE THREAD

**Issue by Bhanu-code** [WeMakeDevs/roadmaps#484]
### Which field of community (DevOps/Opensource/Web/Web3/Android/Devrel) you want to add, drop the links?

Web

![Inkedocrasound](https://user-images.githubusercontent.com/77599001/227832457-8e22ebca-0b38-4d0a-bd04-0378b17cd61f.jpg)

**Comment by Bhanu-code** [comment]
please assign me  to fix this.

**Comment by siddhant-khisty** [comment]
Hey @Bhanu-code, feel free to open a PR for this

**Comment by Mihir-Raj-Singh** [comment]
Hey @siddhant-khisty 
- Please close this issue if it already get resolved.
