### ISSUE TITLE
Roadmap on how to start blogging.

### ISSUE THREAD

**Issue by parthshr370** [WeMakeDevs/roadmaps#487]
### Description

It would be great if you could make a roadmap about tech blogging and blogging in general . How to start , what all platforms are available , what should first blog look like etc

**Comment by mnik7044** [comment]
Hey @siddhant-khisty Is anyone working on this issue if not I would love to work on it.

**Comment by siddhant-khisty** [comment]
There are already many video resources made for this. There isn't a roadmap per se for this topic.
