### ISSUE TITLE
[Bug] Broken link in Frontend Roadmap

### ISSUE THREAD

**Issue by Rishav1707** [WeMakeDevs/roadmaps#492]
### Description

The link of one of the communities is broken in the Join communities section.

![communities](https://user-images.githubusercontent.com/97666287/228747619-6e046827-22d1-490f-953d-d57b6df06827.png)

### Screenshots

https://user-images.githubusercontent.com/97666287/228747652-48406474-78be-42b3-91a1-694d846d6b55.mp4

**Comment by gambhirsamarth** [comment]
Created  a PR for the same. Kindly Approve #493

**Comment by siddhant-khisty** [comment]
Closing as fixed
