### ISSUE TITLE
Add job platform section to repository 

### ISSUE THREAD

**Issue by ganeshpatil386386** [WeMakeDevs/roadmaps#498]
### Description

After following roadmaps people need platforms to apply for the jobs would be great if we can add good job searching portal section to the repository.

**Comment by Sandeep-RN** [comment]
We already do have "Job-Boards" inside all the roadmaps which consist of multiple job platforms related to that specific roadmap where people can search for and apply for jobs.

**Comment by siddhant-khisty** [comment]
We already have job boards in every roadmap
