### ISSUE TITLE
Language-Based Project Grouping

### ISSUE THREAD

**Issue by priynshuchouhn** [WeMakeDevs/roadmaps#508]
### Description

The Language-Based Project Classification feature would allow users to easily classify and see projects based on the programming language used to develop them. This would involve grouping together all projects that were developed using a specific language, such as JavaScript, and displaying them in a separate section or category.

This would make it easier for users to quickly access and manage projects based on their programming language of choice. For instance, if a user primarily works with JavaScript, they could easily find and access all of their JavaScript projects in one place, rather than having to sort through a mixed list of projects in various programming languages.

**Comment by siddhant-khisty** [comment]
This is not relevant since we're including only one or at the most 2 languages per roadmap. These roadmaps are designed from the perspective of absolute beginners, hence including multiple languages would simply lead to confusion

**Comment by priynshuchouhn** [comment]
I faced difficulty finding the relevant programming language project I am learning in the Fullstack development roadmap. I need to check every project to see if it was developed using my preferred language or not.
