### ISSUE TITLE
Links opening in the same tab

### ISSUE THREAD

**Issue by Saptarshi-Bandopadhyay** [WeMakeDevs/roadmaps#511]
All the links in the repo open in the same tab making it troublesome to open another resource simultaneously. We can explicitly open the link in a new tab but it would be better to implicitly have the link open in a new tab when we click it.

**Comment by Saptarshi-Bandopadhyay** [comment]
surely we can, but what i'm suggesting is that it would be better if it automatically opens in a new tab, just a small enhancement in the user experience

**Comment by kaiwalyakoparkar** [comment]
@Saptarshi-Bandopadhyay let me know if you would like to work on this issue

**Comment by siddhant-khisty** [comment]
Hey, @Saptarshi-Bandopadhyay you can open one PR for every roadmap. That makes it easy for us as well to review.

**Comment by Saptarshi-Bandopadhyay** [comment]
Sure, On it.

**Comment by Saptarshi-Bandopadhyay** [comment]
Hey @kaiwalyakoparkar @siddhant-khisty sorry for the trouble but it seems that github markdowns doesn't suuport this feature at all, even if I use html anchor tag with " target='_blank' " it gets scrubbed off when it's rendered.

Sorry for opening an issue without knowing if there was a possible solution.

**Comment by kaiwalyakoparkar** [comment]
No worries @Saptarshi-Bandopadhyay that's alright. Thank you so much for finding the issue and bringing it to the notice :)
