### ISSUE TITLE
Add a notes section to the roadmap page

### ISSUE THREAD

**Issue by manyhapp** [WeMakeDevs/roadmaps#522]
### Description

Add a notes section to the roadmap where students can submit their notes

**Comment by siddhant-khisty** [comment]
I don't think this is a good idea. This repository is meant as a path to break into a particular domain of software. Moreover, if we add notes, 1000s of folks might add notes and it would become way too cluttered. Instead it would be a better idea if folks created their own repository for learning, and push their code + notes into thoese.
