### ISSUE TITLE
Data Science and MachineLearning Roadmap

### ISSUE THREAD

**Issue by chaitanyakatore** [WeMakeDevs/roadmaps#559]
### Description

you should add DATA SCIENCE and Machine Learning Engineer roadmap for the interested folks

**Comment by freescetic** [comment]
Yeah waiting for this one from you guys.

**Comment by 672385** [comment]
assign me I can share

**Comment by niks6600** [comment]
When will this ml/ai roadmap will be updated?Any ETA?

**Comment by chaitanyakatore** [comment]
I am working on this issue 
it will be available soon
