### ISSUE TITLE
[FEATURE] Add a new HTML resource under Learning HTML

### ISSUE THREAD

**Issue by SanskritiGupta05** [WeMakeDevs/roadmaps#575]
### Description

Add a new HTML resource under Learning HTML > HTML tutorial in Readme.md 

### Screenshots

<img width="441" alt="image" src="https://github.com/WeMakeDevs/roadmaps/assets/77205923/f7be5e3c-0883-41d8-954c-cad6ef4717be">

**Comment by KshitizRana** [comment]
May I work on this issue?
Please assign it to me.
