### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Paarth11** [WeMakeDevs/roadmaps#590]
### Description

Register section not working

### Screenshots

<img width="960" alt="image" src="https://github.com/WeMakeDevs/roadmaps/assets/111861185/b637e9be-3d6b-4015-aa9c-1cca685832a1">

**Comment by gopalmani** [comment]
working for me. 
<img width="1680" alt="Screenshot 2023-07-04 at 6 58 56 PM" src="https://github.com/WeMakeDevs/roadmaps/assets/45264570/9ba0fc41-f446-4ca8-99b9-a24a1d6c6d18">

**Comment by siddhant-khisty** [comment]
@Paarth11 I guess this might be your internet connection. We've tried to reproduce the issue but have been unsuccessful at it hence closing this issue
