### ISSUE TITLE
Communities Discord link is invalid or expired

### ISSUE THREAD

**Issue by SaumyaBhushan** [WeMakeDevs/roadmaps#591]
### Description

**Issue**
The communities links inside Open Source folder (https://github.com/WeMakeDevs/roadmaps/tree/main/Open-Source/Communities) seems to be expired or invalid . 

**Solution**
We can update it with the new discord link or their website URLs

**Comment by SaumyaBhushan** [comment]
Hey @siddhant-khisty  For me , inside this directory https://github.com/WeMakeDevs/roadmaps/tree/main/Open-Source/Communities none of the links are working .

**Comment by siddhant-khisty** [comment]
@SaumyaBhushan That's odd. They seem to work for me. can you share a screenshot or screen recording of what's happening?

**Comment by SaumyaBhushan** [comment]
![Screenshot from 2023-07-11 10-35-24](https://github.com/WeMakeDevs/roadmaps/assets/76432998/0a3dd1e7-1dd6-4c6d-ab7a-8008e6e54969)

**Comment by Jashan143** [comment]
Hey, @SaumyaBhushan, it happens when we try to open links on a PC, but it doesn't happen if you open them on a mobile phone.

**Comment by siddhant-khisty** [comment]
This is really weird. I'm not having any issues opening the links on either phone or desktop. Can you folks try to log into the browser version of discord and then try? If it's still not working can you try either in incognito mode or a different browser?

**Comment by kaiwalyakoparkar** [comment]
If the problem still persists do reachout with the specific links not working

**Comment by SaumyaBhushan** [comment]
Hey @siddhant-khisty and @kaiwalyakoparkar ! It's working fine from my mobile. Thanks for your constant help . 

For PC not a single link inside communities folder is working for me ☹️ but it's fine with my mobile phone 🙂

**Comment by SaumyaBhushan** [comment]
I think we can close the issue on the basis of above discussion. 🤔
