### ISSUE TITLE
[Bug] Flutter roadmap not in readme

### ISSUE THREAD

**Issue by mohitvdx** [WeMakeDevs/roadmaps#594]
### Description

Link for the flutter roadmap is not in the readme page.

### Screenshots

<img width="1030" alt="Screenshot 2023-07-11 at 12 54 05 PM" src="https://github.com/WeMakeDevs/roadmaps/assets/112820522/782751ba-f86d-459e-bf01-dfbcf893314a">

**Comment by GauravDhak** [comment]
i want to work on this **issue**, can you assign me @mohitvdx 
### REDME.md

**Comment by siddhant-khisty** [comment]
Outdated issue
