### ISSUE TITLE
[FEATURE] React-Native Roadmap is not available

### ISSUE THREAD

**Issue by SoumyadeepOSD** [WeMakeDevs/roadmaps#596]
### Description

There is a roadmap of android development that is totally in Java & XML. React-Native is a JS framework for mobile app development. 

### Screenshots

![image](https://github.com/WeMakeDevs/roadmaps/assets/115442240/f481dc7b-a338-4dcc-b145-25310d22228b)

This roadmap should be added under a new section "React-native development" or this should be added under "Android development"

### Additional information

No

**Comment by VaishnavVerma** [comment]
because react native comes under WebDev
