### ISSUE TITLE
[FEATURE] Links containing the same content should be tagged as Alternatives 

### ISSUE THREAD

**Issue by rudransh-shrivastava** [WeMakeDevs/roadmaps#600]
### Description

Links that contain the same content should be tagged as "Alternatives" (or something similar) to avoid confusion.

### Screenshots

![image](https://github.com/WeMakeDevs/roadmaps/assets/125893371/c9bb141a-c592-4ee7-83ec-6d6d2b207fde)

### Additional information

I can help with this change.

**Comment by rudransh-shrivastava** [comment]
How do you guys think We can do this?

By adding a "Alt Resource" text before the links create confusion as there can be many Concepts with multiple links like this below.

![image](https://github.com/WeMakeDevs/roadmaps/assets/125893371/48dd2039-81de-4bf0-a206-2a64c2e35bbe)

We can also add numbers before the links to avoid this confusion like below

![image](https://github.com/WeMakeDevs/roadmaps/assets/125893371/cdb97f15-19e1-419e-974e-fa6bc8a25652)

**Comment by sayande717** [comment]
We may also nest it within topics like:
- How does Internet Work?
- - Resource 1
- - Resource 2
- - Resource 3
... and so on

**Comment by siddhant-khisty** [comment]
I like the idea proposed by @sayande717. This can work pretty well. If I recall correctly, the flowchart which existed on the old website was structured in a similar manner

**Comment by sayande717** [comment]
I noticed that there's already an open pull-request which aims to solve this issue. So, @siddhant-khisty, should I create another PR with my proposed changes?

**Comment by siddhant-khisty** [comment]
@sayande717 yes. Let's wait for a while and give them a chance to solve this. If the PR stays inactive for over a week, feel free to take over

**Comment by KUNDAN1334** [comment]
@siddhant-khisty now its fine or required some more changes ?

**Comment by Prafful-Rastogi** [comment]
Is it still not resolved. I would like to take this issue.

**Comment by KalliopiPliogka** [comment]
Hello, I see that this issue is  open, I would like to contribute.

**Comment by siddhant-khisty** [comment]
Hey @KalliopiPliogka Feel free to work on it. There's already a PR open for the backend roadmap. Feel free to make a PR for one of the other roadmaps
