### ISSUE TITLE
[Bug] <description>

### ISSUE THREAD

**Issue by zaidkaladia** [WeMakeDevs/roadmaps#614]
### Description

Issue Summary:
The home page of the website (https://wemakedevs.org/#courses) contains a typo in the "Courses" section. The word "mentor" is used instead of "mentoring" in the following sentence:

"We cover every topic in detail with a hands-on approach and mentor you to stand out to get opportunities by breaking all the barriers."

Expected Correction:
The correct word should be "mentoring," and the sentence should be updated as follows:

"We cover every topic in detail with a hands-on approach and mentoring you to stand out to get opportunities by breaking all the barriers."

Context:
This issue pertains to the website's home page, specifically the "Courses" section, where the mentioned sentence is displayed. The typo might cause confusion for users and should be rectified to maintain a professional and polished appearance.

Steps to Reproduce::
1, Visit the home page of the website (https://wemakedevs.org/#courses).
2, Scroll down to the "Courses" section.
3, Observe the sentence with the typo containing the word "mentor."

Proposed Solution:
To address this issue, we need to replace the word "mentor" with "mentoring" in the mentioned sentence. This correction will ensure grammatical accuracy and enhance the overall quality of the website's content.

### Screenshots

<img width="1366" alt="Screenshot 2023-07-24 at 12 46 51 PM" src="https://github.com/WeMakeDevs/roadmaps/assets/102306774/1895c950-cfba-4236-ad7f-5bbfcb0fba14">

### Additional information

As a contributor, I'm willing to provide the necessary changes to resolve this typo. Kindly let me know if there are any specific guidelines for making contributions to the website's content.

Let's work together to maintain the excellence of the website and provide a seamless experience for its users. If there's any further information required, please don't hesitate to reach out. Thank you!

P.S: this is my first contribution and I want it to be to help this community and start my journey from where i have learned. It would be a great help to give me a chance.

**Comment by siddhant-khisty** [comment]
This isn't the right repository for the issue. Please open this issue in the website repo :)
