### ISSUE TITLE
Job Boards you can apply in Blockchain

### ISSUE THREAD

**Issue by RModhilalgohind** [WeMakeDevs/roadmaps#617]
### Description

Job Boards you can apply in Blockchain, Indeed and Glassdoor are going to the same website to Indeed

### Screenshots

<img width="466" alt="Screenshot 2023-08-01 at 12 44 31 AM" src="https://github.com/WeMakeDevs/roadmaps/assets/100789321/e0956028-8560-4f48-94f0-8208727ad73d">

**Comment by siddhant-khisty** [comment]
Hey @RModhilalgohind feel free to work on this. You can either remove the glassdoor board or change it's link to point to the correct address. Either works
