### ISSUE TITLE
Cybersecurity Roadmap

### ISSUE THREAD

**Issue by ctnkaan** [WeMakeDevs/roadmaps#84]
I've added cybersecurity communities, open-source security projects and job boards. I've double checked every link.
For validation I'm not a pro but I have been training in cybersecurity for more than 4 months on my spare time. I'm almost "Omni" rank on TryHackMe.

**Comment by kaiwalyakoparkar** [comment]
@ctnkaan thank you so much for this 🚀 . We have cybersecurity soon coming up in our roadmap :)

**Comment by AniketNS** [comment]
Hey @kaiwalyakoparkar, assign this to me. I'll create the PR as soon as possible.

**Comment by ctnkaan** [comment]
@AniketNS Hey Aniket. I already made the PR long ago. Just waiting for the website to include it. #85
